name       : fbreader
homepage   : https://fbreader.org
version    : 0.99.4
release    : 7
source     :
    - https://fbreader.org/files/desktop/fbreader-sources-0.99.4.tgz : 3d7c31d5ea314589d2a963290ad16f4d3d631a41e802b8b39f8be0c9f71eb8e9
license    : GPL-2.0-or-later
component  : office.viewers
summary    : Favorite Book Reader
description: |
    FBReader is a free (and ad-free) multi-platform ebook reader. Supports popular ebook formats ePub, fb2, mobi, rtf, html, plain text, and a lot of other formats. Provides access to popular network libraries that contain a large set of ebooks. Download books for free or for a fee. Add your own catalog.Highly customizable. Choose colors, fonts, page turning animations, dictionaries, bookmarks, etc. to make reading as convenient as you want.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(fribidi)
    - pkgconfig(sqlite3)
    - pkgconfig(libunibreak)
    - bzip2-devel
setup      : |
    %apply_patches
build      : |
    export TARGET_ARCH=desktop
    export UI_TYPE=qt4
    export TARGET_STATUS=release
    %make -j1
install    : |
    %make_install LIBDIR=%libdir% -j1

