name       : fbreader
homepage   : https://fbreader.org
version    : 0.99.4
release    : 4
source     :
    - https://fbreader.org/files/desktop/fbreader-sources-0.99.4.tgz : 3d7c31d5ea314589d2a963290ad16f4d3d631a41e802b8b39f8be0c9f71eb8e9
license    : GPL-2.0
component  : office
summary    : Favorite Book Reader
description: |
    FBReader is a free (and ad-free) multi-platform ebook reader. Supports popular ebook formats ePub, fb2, mobi, rtf, html, plain text, and a lot of other formats. Provides access to popular network libraries that contain a large set of ebooks. Download books for free or for a fee. Add your own catalog.Highly customizable. Choose colors, fonts, page turning animations, dictionaries, bookmarks, etc. to make reading as convenient as you want.
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(QtCore)
    - pkgconfig(sqlite3)
    - pkgconfig(libunibreak)
setup      : |
    ln -s /usr/bin/moc-qt4 /usr/bin/moc
    ln -s /usr/bin/qmake-qt4 /usr/bin/qmake
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
build      : |
    %make
install    : |
    %make_install


